name: firebase_user_repository
description: "firebase_user_repository for flutter_user package"
version: 6.0.0
repository: https://github.com/Iconica-Development/flutter_user

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  user_repository_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^6.0.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0

dev_dependencies:
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^7.0.0
