name: user_repository_interface
description: "user_repository_interface for flutter_user package"
version: 6.0.0

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
