# .github/workflows/trigger-docs-update.yml
name: Trigger Documentation Update

on:
    release:
    workflow_dispatch:


jobs:
  trigger-doc-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger documentation workflow
        env:
            DOC_PAT: ${{ secrets.DOC_PAT }}
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $DOC_PAT" \
          "https://api.github.com/repos/Iconica-Development/iconica_component_documentation/actions/workflows/documentation.yml/dispatches" \
          -d "{\"ref\":\"master\",\"inputs\":{\"repository_url\":\"$REPO_URL\"}}"
